var peopleData=[]
export default peopleData= [ {
  id: 1,
  fname: 'Varnika',
  lname: "Sharma",
  city: "New Delhi",
  country: "India",
  phone: "91XXXXXX",
  summary: "Records Inspector",
  aircraft: "NA",
  helicopter: "XXX",
  power_plant: "NA",
  approve: true,
  disapprove: false,
  available: true,
  not_available: false,
  rating: 3,
  like: true,
},
{
  id: 2,
  fname: 'Shubham',
  lname: "Jain",
  city: "Rohtak",
  country: "India",
  phone: "91XXXXXX",
  summary: "Physical Inspector",
  aircraft: "NA",
  helicopter: "NA",
  power_plant: "NA",
  approve: false,
  disapprove: true,
  available: true,
  not_available: false,
  rating: 1,
  like: true,
},
{
  id: 3,
  fname: 'Kanishtha',
  lname: "Sharma",
  city: "New Delhi",
  country: "India",
  phone: "91XXXXXX",
  summary: "Project Manager",
  aircraft: "XXXA",
  helicopter: "XXX",
  power_plant: "NA",
  approve: false,
  disapprove: true,
  available: false,
  not_available: true,
  rating: 5,
  like: false,
},
{
  id: 4,
  fname: 'Aayush',
  lname: "Jain",
  city: "Mohali",
  country: "India",
  phone: "91XXXXXX",
  summary: "Records Inspector",
  aircraft: "XXXB",
  helicopter: "XXX",
  power_plant: "NA",
  approve: true,
  disapprove: false,
  available: true,
  not_available: false,
  rating: 4,
  like: true,
},
{
  id: 5,
  fname: 'Geet',
  lname: "Arora",
  city: "Mohali",
  country: "India",
  phone: "91XXXXXX",
  summary: "Quality Engineer",
  aircraft: "NA",
  helicopter: "NA",
  power_plant: "NA",
  approve: false,
  disapprove: true,
  available: false,
  not_available: true,
  rating: 2,
  like: false,
},
{
  id: 6,
  fname: 'Anjali',
  lname: "Sahrawat",
  city: "New Delhi",
  country: "India",
  phone: "91XXXXXX",
  summary: "Planning Engineer",
  aircraft: "XXX",
  helicopter: "XXX",
  power_plant: "NA",
  approve: true,
  disapprove: false,
  available: true,
  not_available: false,
  rating: 5,
  like: false,
},
{
  id: 7,
  fname: 'Mukesh',
  lname: "Sharma",
  city: "Mumbai",
  country: "India",
  phone: "91XXXXXX",
  summary: "Records Inspector",
  aircraft: "NA",
  helicopter: "NA",
  power_plant: "NA",
  approve: false,
  disapprove: false,
  available: false,
  not_available: false,
  rating: 3,
  like: true,
},
{
  id: 8,
  fname: 'Rihaan',
  lname: "Prashar",
  city: "New Delhi",
  country: "India",
  phone: "91XXXXXX",
  summary: "Records Inspector",
  aircraft: "XXX",
  helicopter: "XXX",
  power_plant: "NA",
  approve: true,
  disapprove: false,
  available: true,
  not_available: false,
  rating: 0,
  like: true,
},
{
  id: 9,
  fname: 'Raghav',
  lname: "Arora",
  city: "New Delhi",
  country: "India",
  phone: "91XXXXXX",
  summary: "Planning Engineer",
  aircraft: "NA",
  helicopter: "XXX",
  power_plant: "XXX",
  approve: true,
  disapprove: false,
  available: false,
  not_available: true,
  rating: 4,
  like: false,
},
{
  id:10,
  fname: 'Aditi',
  lname: "Jain",
  city: "Mohali",
  country: "India",
  phone: "91XXXXXX",
  summary: "Aviation Technical Consultant",
  aircraft: "XXX",
  helicopter: "XXX",
  power_plant: "NA",
  approve: false,
  disapprove: true,
  available: false,
  not_available: true,
  rating: 1,
  like: true,
},
]